
x-svc: &service
  env_file:
    - "/app/search.marginalia.nu/env/service.env"
  volumes:
    - ms_conf:/wmsa/conf:ro
    - ms_model:/wmsa/model:ro
    - ms_data:/wmsa/data:ro
    - ms_logs:/var/log/wmsa
    - "/app/index/9/current:/idx"
    - "/app/index/9/work:/work"
    - "/app/index/9/backup:/backup"
    - "/app/index/9/storage:/storage"
  restart: unless-stopped
  networks:
    - wmsa
  environment:
    - "WMSA_SERVICE_NODE=9"


services:
  index-service-9:
    <<: *service
    image: "marginalia.nu/index-service"
    container_name: "index-service-9"
  executor-service-9:
    <<: *service
    image: "marginalia.nu/executor-service"
    container_name: "executor-service-9"
networks:
  wmsa:
volumes:
  ms_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/logs
  ms_model:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/model
  ms_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/conf
  ms_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/data
