x-svc: &service
  env_file:
    - "/app/search.marginalia.nu/env/service.env"
  volumes:
    - ms_conf:/wmsa/conf:ro
    - ms_model:/wmsa/model:ro
    - ms_data:/wmsa/data:ro
    - ms_logs:/var/log/wmsa
  networks:
    - wmsa
  restart: unless-stopped
services:
  query-service:
    <<: *service
    image: "marginalia.nu/query-service"
    container_name: "query-service"
  search-service:
    <<: *service
    image: "marginalia.nu/search-service"
    container_name: "search-service"
    expose:
    - 80
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.search-service.rule=PathPrefix(`/`)"
    - "traefik.http.routers.search-service.entrypoints=search"
    - "traefik.http.routers.search-service.middlewares=add-xpublic"
    - "traefik.http.routers.search-service.middlewares=add-public"
    - "traefik.http.middlewares.add-xpublic.headers.customrequestheaders.X-Public=1"
    - "traefik.http.middlewares.add-public.addprefix.prefix=/public"
  assistant-service:
    <<: *service
    image: "marginalia.nu/assistant-service"
    container_name: "assistant-service"
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.assistant-service.rule=PathPrefix(`/screenshot`)"
      - "traefik.http.routers.assistant-service.entrypoints=search"
      - "traefik.http.routers.assistant-service.middlewares=add-xpublic"
      - "traefik.http.routers.assistant-service.middlewares=add-public"
      - "traefik.http.middlewares.add-xpublic.headers.customrequestheaders.X-Public=1"
      - "traefik.http.middlewares.add-public.addprefix.prefix=/public"
  api-service:
    <<: *service
    image: "marginalia.nu/api-service"
    container_name: "api-service"
    expose:
    - "80"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api-service.rule=PathPrefix(`/`)"
    - "traefik.http.routers.api-service.entrypoints=api"
    - "traefik.http.routers.api-service.middlewares=add-xpublic"
    - "traefik.http.routers.api-service.middlewares=add-public"
    - "traefik.http.middlewares.add-xpublic.headers.customrequestheaders.X-Public=1"
    - "traefik.http.middlewares.add-public.addprefix.prefix=/public/api"
  dating-service:
    <<: *service
    image: "marginalia.nu/dating-service"
    container_name: "dating-service"
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dating-service.rule=PathPrefix(`/`)"
      - "traefik.http.routers.dating-service.entrypoints=dating"
      - "traefik.http.routers.dating-service.middlewares=add-xpublic"
      - "traefik.http.routers.dating-service.middlewares=add-public"
      - "traefik.http.middlewares.add-xpublic.headers.customrequestheaders.X-Public=1"
      - "traefik.http.middlewares.add-public.addprefix.prefix=/public"
  explorer-service:
    <<: *service
    image: "marginalia.nu/explorer-service"
    container_name: "explorer-service"
    expose:
    - 80
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.explorer-service.rule=PathPrefix(`/`)"
    - "traefik.http.routers.explorer-service.entrypoints=explore"
    - "traefik.http.routers.explorer-service.middlewares=add-xpublic"
    - "traefik.http.routers.explorer-service.middlewares=add-public"
    - "traefik.http.middlewares.add-xpublic.headers.customrequestheaders.X-Public=1"
    - "traefik.http.middlewares.add-public.addprefix.prefix=/public"
  control-service:
    <<: *service
    image: "marginalia.nu/control-service"
    container_name: "control-service"
    expose:
    - 80
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.control-service.rule=PathPrefix(`/`)"
    - "traefik.http.routers.control-service.entrypoints=control"
    - "traefik.http.routers.control-service.middlewares=add-xpublic"
    - "traefik.http.routers.control-service.middlewares=add-public"
    - "traefik.http.middlewares.add-xpublic.headers.customrequestheaders.X-Public=1"
    - "traefik.http.middlewares.add-public.addprefix.prefix=/public"
networks:
  wmsa:
volumes:
  ms_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/logs
  ms_model:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/model
  ms_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/conf
  ms_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/search.marginalia.nu/data
