services:
  browserless:
    image: "ghcr.io/browserless/chromium"
    container_name: "headlesschrome"
    env_file:
    - "/app/search.marginalia.nu/env/browserless.env"
    networks:
      - headlesschrome

networks:
  headlesschrome:
