services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/traefik-conf/traefik-dynamic.yml"
      - "--entrypoints.search.address=:80"
      - "--entrypoints.control.address=:81"
      - "--entrypoints.api.address=:82"
      - "--entrypoints.dating.address=:83"
      - "--entrypoints.explore.address=:84"
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8081:81"
      - "127.0.0.1:8082:82"
      - "127.0.0.1:8083:83"
      - "127.0.0.1:8084:84"
      - "127.0.0.1:8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/app/trafeik:/traefik-conf:ro"
    networks:
      - wmsa
    restart: unless-stopped
networks:
  wmsa:
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/db
