version: '3.1'

services:
  zookeeper1:
    image: zookeeper
    container_name: "zookeeper1"
    restart: always
    hostname: zookeeper1
    ports:
      - 127.0.0.1:2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      - wmsa
  zookeeper2:
    image: zookeeper
    container_name: "zookeeper2"
    restart: always
    hostname: zookeeper2
    ports:
      - 127.0.0.1:2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      - wmsa
  zookeeper3:
    image: zookeeper
    container_name: "zookeeper3"
    restart: always
    hostname: zookeeper3
    ports:
      - 127.0.0.1:2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      - wmsa
networks:
  wmsa:
    external: true